services:
  blog_strapi_api:
    container_name: blog_strapi_api
    hostname: blog_strapi_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 45573475Ygo-
      POSTGRES_DB: blog-strapi
    ports:
      - 5432:5432
